### ISSUE TITLE
[Feature Request] Add OCLP post-install patch version

### ISSUE THREAD

**Issue by TonyC5** [0xCUB3/About-This-Hack#24]
More and more hackers are using OCLP to extend the life of their legacy Macs and hackintoshes.  It might be helpful if About-This-Hack included the current OCLP version when applicable.  I'm not sure how this would be accomplished, but one way might be to grab the version of OpenCore-Patcher.app in /Library/Application Support/Dortania.  

Great app.  Thanks for your hard work!

**Comment by 0xCUB3** [comment]
good idea! I will try to see if there's a way to implement this

**Comment by 0xCUB3** [comment]
if anyone has a mac with the opencore legacy patcher and is willing to help me get it into the code, please let me know! I can't add this feature since I don't own a mac running the patcher right now.

**Comment by TonyC5** [comment]
I have OCLP installed.  There are two ways that I know to "extract" the current OCLP patch version: 

- In '/Library/Application Support/Dortania' there is the application 'OpenCore - Patcher.app'.  The version of this app is the version of the applied OCLP patches
- In EFI/OC/config.plist, there is the property NVRAM > Add > 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102 > OCLP-Version.  This property (a String) is supposed to be the version of OCLP that generated the EFI.  It is less reliable (my opinion) than the version of OpenCore - Patcher.app.

**Comment by 0xCUB3** [comment]
in the application support folder, where specifically can the version of the app be found?

**Comment by TonyC5** [comment]
I'm not sure of the .app file structure.  If I perform "GetInfo" on the file (in Finder), I see the following:

![Screenshot 2023-05-27 at 3 04 57 PM](https://github.com/0xCUB3/About-This-Hack/assets/28421182/dae55d79-e1e4-436e-9bd3-a230ac1a282b)

**Comment by 0xCUB3** [comment]
Thank you. It must be somewhere within the Info.plist of the app.

**Comment by TonyC5** [comment]
Good guess.  I looked in the info.plist: It is "Bundle version string (short)"

**Comment by 0xCUB3** [comment]
thank you! ❤️ I will try to add this into the next major release; the next minor release (0.7.2) will primarily consist of bug fixes!

**Comment by TonyC5** [comment]
Thank you!

**Comment by matxpa** [comment]
Hi
You could see Logs in ($HOME) "~/Library/Logs/Dortania/"
Regards

**Comment by 0xCUB3** [comment]
I'm curious... since it's NVRAM data, it should be possible to get the value from terminal, right? 

Try this command: `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:OCLP-Version`

@matxpa @TonyC5

**Comment by TonyC5** [comment]
The value OCLP-Version will only exist in NVRAM (if it does) because it is in the OC config.plist as I mentioned [here](https://github.com/0xCUB3/About-This-Hack/issues/24#issuecomment-1565654306).  When OCLP is used to generate the OC EFI for a real Mac (OCLP is not intended for hacks), it will include OCLP-Version in the config.plist.  Hackintosh users may not include OCLP-Version in their OC config.plist, so in my opinion, using NVRAM is an unreliable method for determining whether a hack has been root-patched with OCLP.  As far as I know, the only "sure" way to determine whether OCLP is used to apply root patches on both real Macs and Hacks is to look for the OpenCore-Patcher.app in '/Library/Application Support/Dortania' and if it is present, get the version of OpenCore-Patcher.app.

**Comment by 0xCUB3** [comment]
Why wouldn't it be reliable? If the NVRAM arg doesn't exist, we will not show the OCLP version at all. This is what we do for the OpenCore version as well. 


Could you check if this command works for you, please?

**Comment by TonyC5** [comment]
We're talking past each other.  It's not reliable for Hacks that don't included OCLP-Version in their OC config.plist.

**Comment by 0xCUB3** [comment]
> We're talking passed each other. It's not reliable for Hacks that don't included OCLP-Version in their OC config.plist.

That's what I'm saying. Hackintoshes don't have this value because they don't use OCLP. In this case, I will not add the OCLP version to the output.

**Comment by TonyC5** [comment]
Hacks can use OCLP to apply root patches.

**Comment by 0xCUB3** [comment]
> Hacks can use OCLP to apply root patches.

that's fine. If they are just applying root patches, they aren't really using OCLP.

**Comment by TonyC5** [comment]
That makes no sense.  You need to learn OCLP.

**Comment by 0xCUB3** [comment]
I've used OCLP on my 2011 MacBook Pro and my 2015 MacBook Pro. Using an EFI generated by OCLP is using OCLP. Just applying root patches is not, as you are still using a hackintosh EFI that you created, just with a few extra patches.

**Comment by TonyC5** [comment]
You need to learn how hackintosh users use OCLP.  This discussion is pointless.  Good luck.

**Comment by 0xCUB3** [comment]
> You need to learn how hackintosh users use OCLP. This discussion is pointless. Good luck.

As I said previously, it is not the same. If you believe otherwise, feel free to make a pull request with what you want it to look like and I will consider adding it. However, this is my app, so I am allowed to have liberty with how I structure things.

**Comment by MDNich** [comment]
I suggest we change the tone to a more professional one…let’s try to find a
solution that displays the most information.

**Comment by TonyC5** [comment]
@MDNich  Thanks for adding humor to this post.  All views expressed were professional. The app-owner received feedback and made a call.  That's how this works.

**Comment by matxpa** [comment]
@TonyC5  a little (humility) goes a long way

![Capture d’écran 2023-09-04 à 15 10 47](https://github.com/0xCUB3/About-This-Hack/assets/70573409/fc62e377-1eed-4cbd-bd09-6f6f13c0dfae)

...
wx_gui/gui_sys_patch_display.py:199:                    patch_text = f"{self.constants.computer.oclp_sys_version}, {date}"
...
wx_gui/gui_sys_patch_display.py:201:                    patch_label = wx.StaticText(frame, label="Root Volume last patched:", pos=(-1, patch_label.GetPosition().y + 25))
...
wx_gui/gui_sys_patch_display.py:205:                    patch_label = wx.StaticText(frame, label=patch_text, pos=(available_label.GetPosition().x - 10, patch_label.GetPosition().y + 20))

And the "Root Volume last patched" info come from  "/System/Library/CoreServices/OpenCore-Legacy-Patcher.plist"
See that "plist" content below

![Capture d’écran 2023-09-04 à 16 05 34](https://github.com/0xCUB3/About-This-Hack/assets/70573409/0060d4da-1791-4ff1-a91a-5be82784691c)

You could see that the info shown under "Root Volume last patched" and data in the "plist" are identical.
The lack of URL content 'coz its an OCLP local build (sonoma-dev branch) otherwise with a github OCLP repo downloaded release (OpenCore-Patcher-0.6.9-c9a14e2-20230801.app) it could be as shown below with an URL and a commit value
Commit Information:
    Branch: refs/heads/sonoma-development
    Date: 2023-08-01T13:24:41-06:00
    URL: https://github.com/dortania/OpenCore-Legacy-Patcher/commit/c9a14e242d7fb705ed4b481b6d71f9be39f36638

With the an OCLP local build ( no branch, no URL, only build datetime) as shown below (info from Settings/App on OCLP Main Menu)
Commit Information:
    Branch: Built from source
    Date: 2023-08-31 14:32:35
    URL: N/A

The solution is to extract needed info from "/System/Library/CoreServices/OpenCore-Legacy-Patcher.plist" (if exists)
...
grep -A1 "OpenCore Legacy Patcher" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.<string>?OCLP: ?g' -e 's?</string>?, ?g' 
grep -A1 "Time Patched" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.<string>?Patched: ?g' -e 's?@?at?g' -e 's?</string>??g'
grep -A1 "Commit URL" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.<string>??g' -e 's?</string>??g' | awk -F 'commit/' '{print "Commit: " $NF}' | cut -c 1-15

OCLP: v0.6.9, 
Patched: August 31, 2023 at 11:35:51
Commit: 

Regards

**Comment by TonyC5** [comment]
@matxpa  Yes - your are very humble indeed.  Thank you for providing another example showing that NVRAM is not the way to solve this.

**Comment by matxpa** [comment]
" non-NVRAM approach" may be, ask OCLP Team to do that
"/System/Library/CoreServices/OpenCore-Legacy-Patcher.plist " exists if your Hack had been patched and with the use of bootloader OC OR CLOVER  bootloader regardless of the content of NVRAM.
The aim is to show if you Hack is patched or not and with detailed OCLP info.

**Comment by TonyC5** [comment]
We're in violent agreement.  Your approach does not rely on NVRAM and neither does mine.  Either is fine.

**Comment by matxpa** [comment]
'/Library/Application Support/Dortania/OpenCore-Patcher.app/Contents/Info.plist' is the one of your actual, current OCLP release and may be not the one you've used to patch your Mac or Hack.
Each time you patch a macOS after release upgrade on (a Non Supported  MAC or NEVER supported HACK) with OCLP a new history content of your action in /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist is generated. This file is the only one which can and may contain details of the LAST OCLP PATCH action.

For exemple you've patched your system 15 days ago, today you launch OCLP and a new release is available, OCLP ask you if you want to install this new release and you do it. Your current OCLP release ( /Library/Application Support/Dortania/OpenCore-Patcher.app ) is not the one you've used to patch your Mac/Hack.
The only real info of the LAST OCLP PATCH are available in /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist.

**Comment by TonyC5** [comment]
That's good to know - sounds like a technicality, but who am I to argue?  Using /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist is fine with me and better than the NVRAM approach suggested earlier in this thread.

**Comment by MDNich** [comment]
Here's a question - does the PLIST approach work for EVERYONE who has OCLP? In a way that the NVRAM apparently didn't ?

**Comment by TonyC5** [comment]
Given a choice between OCLP-Version in NVRAM and the plist, the plist is the only choice that works for everyone.

**Comment by matxpa** [comment]
@MDNich Hi

If you own a Mac (patched Mac or Hack) try to see if /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist exists.
If you've used OCLP to patch a Non Supported (M/H)ac(k) this plist exists, created or content replaced with new  patch action

**Comment by MDNich** [comment]
Unfortunately I do not - hence why I stayed out of this discussion until now

**Comment by 0xCUB3** [comment]
Alright my angry little elves (@TonyC5 and @matxpa (although you are not as angry 😄)). Your wish has been granted. Please test this latest build to make sure everything is functioning properly: https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing

**Comment by TonyC5** [comment]
Thanks.  I downloaded the new version on my HackBookPro6,2 (Dell Latitude E6410) running Ventura 13.5.1 and patched with OCLP 0.6.8. 

About This Hack Beta
![Screenshot 2023-09-05 at 1 28 11 AM](https://github.com/0xCUB3/About-This-Hack/assets/28421182/ea1eea63-9a42-4196-8c7b-258e1f9ad8b5)

About This Hack 0.9.1
![Screenshot 2023-09-05 at 1 32 46 AM](https://github.com/0xCUB3/About-This-Hack/assets/28421182/6946a62d-3fa1-4184-be11-637c68469a7b)

**Comment by matxpa** [comment]
@0xCUB3 
Hi
About Storage tab : doesn't work if two or more Disk internal and/or external have the same name (ex: "Macintosh HD")

HardwareCollector.swift
...
    static func getStorageType() -> Bool {
        let name = "\(HCStartupDisk.getStartupDisk())"
        print("Startup Disk Name " + name)
        let storageType = run("diskutil info \"\(name)\" | grep 'Solid State'")
        
        return storageType.contains("Yes")
...

Startup disk is (and always were) "/"  and (mine) is called "Macintosh HD"
So if i execute the command diskutil info "Macintosh HD" | grep "Solid State") as in HardwareCollector.swift
where "name" = "Macintosh HD", result is "   Solid State:               Info not available" so picture will be HDD (default)
'coz there are two SSD called "Macintosh HD", so
-Picture (startupDiskImage.image) has default value (HDD)
-storageValue.stringValue (startup disk name) is empty
-storageAmount.doubleValue is empty 

With your first zipped App dowloaded yesterday Storage tab doesn't  work with one or two SSD called "Macintosh HD"
With your second zipped App dowloaded yesterday Storage tab  works fine with one SSD but doesn't with two SSD called "Macintosh HD".

Another thing:
I launch "About This Hack" (first launch) "~/.ath" and data files are created Overview is shown with detailed data i change tab and launch Displays in remove (delete) "~/.ath" ("About This Hack" always active) I come back to Overview I lost detailed info.
In ViewController.swift (line +/- 85         if (!HardwareCollector.dataHasBeenSet) {HardwareCollector.getAllData()}
I moved terminating bracket "}" after all variables init, (line +/- 149 after the line code             serialToggle.isTransparent = true) and each time you show Overview variables content is not reloaded (it had been done at launch of the appli) so removing "~/.ath" causes No Problem.

And why "~/.ath" is not removed when you leave "About This Hack" between two launches data may have change.

Regards

**Comment by matxpa** [comment]
@0xCUB3 

Your last modifications, last downloaded "app"

![Capture d’écran 2023-09-06 à 14 16 49](https://github.com/0xCUB3/About-This-Hack/assets/70573409/4562acd3-71d6-4630-afec-99c6a9fca58b)

HCBootloader.swift
...
          if run("grep -A1 \"OpenCore Legacy Patcher\" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.?OCLP: ?g' -e 's??, ?g'").contains("No") ...

result is : ", , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , "

Try this 5 commands on a term window (if you have a patched Mac or Hack), otherwise no result 

OCLPRelease=$(grep -A1 "OpenCore Legacy Patcher" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.*<string>?Patcher OCLP ?' -e 's?<\/string>??')
OCLPDateTime=$(grep -A1 "Time Patched" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.*<string>??' -e 's?<\/string>??' -e 's/@ /(/')
OCLPCommit=$(grep -A1 "Commit URL" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.*<string>??' -e 's?<\/string>??' | awk -F'/' '{print substr($NF,1,7)}')
OCLPDisplayValue=$(echo "${OCLPRelease}(${OCLPCommit}) ${OCLPDateTime})")
echo "${OCLPDisplayValue}"

and you'll see (displayed values come from /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist on my Laptop)
Patcher OCLP v0.6.9(c9a14e2) September 01, 2023 (17:18:27)

Regards

**Comment by 0xCUB3** [comment]
@matxpa I don't have a patched Mac or hackintosh, so unfortunately I can't really be of help there. I wonder why it's doing that...

**Comment by TonyC5** [comment]
@0xCUB3 and @matxpa  - you have clearly demonstrated yourselves to be the experts, so I'm going to watch the progress.  Forgive what may be a remedial suggestion, but couldn't @0xCUB3  Test without patching simply by placing @matxpa 's plist in /System/Library/CoreServices after manually creating the folder?

**Comment by matxpa** [comment]
@0xCUB3 @TonyC5 

And like this

![Capture d’écran 2023-09-06 à 22 54 45](https://github.com/0xCUB3/About-This-Hack/assets/70573409/81320443-cfcf-4b88-a82c-6d7232345174)

with ToolTip on BootLoader

Regards

**Comment by TonyC5** [comment]
Serial Number?

**Comment by matxpa** [comment]
Hi @deeveedee

Serial Number?  May be I forgot to hide it. Coz you wanna steal it ? 

Not thrilled with relegating all OCLP info to a tool tip : we're waiting your way to do that.

Regards

**Comment by matxpa** [comment]
Hi @0xCUB3 

And now the same (Sonoma 14.0 Dev beta 7) with Clover

![Capture d’écran 2023-09-07 à 16 36 44](https://github.com/0xCUB3/About-This-Hack/assets/70573409/9bd914c5-f87f-45d8-a878-2f645643efef)

Next step will be with a fake NOT patched OS (ie. file /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist  renamed /System/Library/CoreServices/OpenCore-Legacy-Patcher.plast which one doesn't exist)

ls -l /System/Library/CoreServices/OpenCore-Legacy-Patcher.plast
ls: /System/Library/CoreServices/OpenCore-Legacy-Patcher.plast: No such file or directory

So we wouldn't see OCLP detailed info with Bootloader (ToolTip)

Regards

**Comment by matxpa** [comment]
Hi @0xCUB3

A NOT OCLP patched OS

![Capture d’écran 2023-09-07 à 17 03 17](https://github.com/0xCUB3/About-This-Hack/assets/70573409/e55a89f1-3a1c-424a-a1d5-de595a7feef2)

you can't see OCLP detailed info with Bootloader (ToolTip)

Regards

**Comment by 0xCUB3** [comment]
Added in the latest commit
