### ISSUE TITLE
missing compiled version

### ISSUE THREAD

**Issue by kaoskinkae64** [0xCUB3/About-This-Hack#41]
missing compiled version it is important to keep that on (.......) since those of us who use the beta versions of the different systems available, both Ventura and Sonoma, it is important to know which version we are using

**Comment by 0xCUB3** [comment]
what exactly do you mean by this?

**Comment by matxpa** [comment]
Hi @0xCUB3 @kaoskinkae64 

It exactly mean that the commit ID (OSBuildNum) lack after OSnum

![Capture d’écran 2023-08-13 à 19 48 47](https://github.com/0xCUB3/About-This-Hack/assets/70573409/d0cf7f60-9f18-43a4-8d2a-bad9dafa6187)

the reason is the '\n' at the end of OSnum and the cell is not scrollable so we can't see OSBuildNum value on the second line.
 
Component to modify
HCVersion.swift --> line 37 replace content        let osVersion = run("sw_vers -productVersion")
                                                                    with       let osVersion = run("sw_vers -productVersion | tr -d '\n'")
HCVersion.swift --> line 82 replace content        return "(" + run("sw_vers -buildVersion") + ")"
                                                                    with       return " (" + run("sw_vers -buildVersion | tr -d '\n'") + ")"

![Capture d’écran 2023-08-13 à 20 00 44](https://github.com/0xCUB3/About-This-Hack/assets/70573409/19edfb97-7690-486a-9e1b-4e3e09cd36fe)

And a cosmetic change in
ViewController.swift --> line 27 replace content    var osNumber = run("sw_vers | grep ProductVersion | cut -c 17-")
                                                                         with    var osNumber = run("sw_vers -ProductVersion")
           and maybe add  a necessary "| tr -d '\n' "   var osNumber = run("sw_vers -ProductVersion | tr -d '\n'")

Regards

**Comment by esafeddie** [comment]
Latest version still not showing full compiled version as previously pointed out like in version 0.8.1 which I have gone back to for that feature.

**Comment by 0xCUB3** [comment]
Oh yeah I see. I will re-implement this in the next release. Sorry about that!

**Comment by 0xCUB3** [comment]
Fixed in latest commit
